# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='friends',
            field=models.TextField(default='[]'),
        ),
    ]
